name: Check T212 Stocks

on:
  schedule:
    - cron: '*/15 13-22 * * 1-5'  # Every 15 mins, 14:00-21:00 UTC, Monday-Friday
  workflow_dispatch:        # Allows manual triggering

permissions:
  contents: write          # Explicitly set permissions

jobs:
  check-stocks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests
          
      - name: Download previous CSV
        run: |
          if [ ! -f t212_current.csv ]; then
            echo "Creating empty CSV file"
            echo "dummy,data" > t212_current.csv
          fi
          
      - name: Run stock checker
        env:
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          RECIPIENTS: ${{ secrets.RECIPIENTS }}
          T212_API_KEY: ${{secrets.T212_API_KEY}}
        run: python stock_checker.py
        
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add t212_current.csv
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update stock data" && git push)
